export const stateManagement = [

   {"order_id": "#1234", "created": "3 min ago", "customers": "Alice Johnson", "total": "$215", "profit": "$130", "status": "Pending"},
   {"order_id": "#5678", "created": "7 min ago", "customers": "Jon Smit", "total": "$412", "profit": "$95", "status": "Confirmed"},
   {"order_id": "#9101", "created": "5 min ago", "customers": "Chris Lee", "total": "$123", "profit": "$54", "status": "Processing"},
   {"order_id": "#1122", "created": "4 min ago", "customers": "Jane Doe", "total": "$334", "profit": "$173", "status": "Shipped"},
   {"order_id": "#2233", "created": "8 min ago", "customers": "Emily Davis", "total": "$456", "profit": "$245", "status": "Cancelled"},
   {"order_id": "#3344", "created": "2 min ago", "customers": "Alice Johnson", "total": "$230", "profit": "$140", "status": "Pending"},
   {"order_id": "#4455", "created": "6 min ago", "customers": "Jon Smit", "total": "$301", "profit": "$189", "status": "Delivered"},
   {"order_id": "#5566", "created": "9 min ago", "customers": "Chris Lee", "total": "$120", "profit": "$60", "status": "Processing"},
   {"order_id": "#6677", "created": "5 min ago", "customers": "Jane Doe", "total": "$340", "profit": "$200", "status": "Shipped"},
   {"order_id": "#7788", "created": "1 min ago", "customers": "Emily Davis", "total": "$271", "profit": "$125", "status": "Confirmed"},
   // {"order_id": "#8899", "created": "7 min ago", "customers": "Alice Johnson", "total": "$305", "profit": "$175", "status": "Cancelled"},
   // {"order_id": "#9900", "created": "6 min ago", "customers": "Jon Smit", "total": "$159", "profit": "$85", "status": "Pending"},
   // {"order_id": "#1357", "created": "4 min ago", "customers": "Chris Lee", "total": "$411", "profit": "$210", "status": "Delivered"},
   // {"order_id": "#2468", "created": "8 min ago", "customers": "Jane Doe", "total": "$287", "profit": "$120", "status": "Processing"},
   // {"order_id": "#3579", "created": "2 min ago", "customers": "Emily Davis", "total": "$496", "profit": "$250", "status": "Confirmed"},
   // {"order_id": "#4680", "created": "3 min ago", "customers": "Alice Johnson", "total": "$250", "profit": "$140", "status": "Cancelled"},
   // {"order_id": "#5791", "created": "9 min ago", "customers": "Jon Smit", "total": "$375", "profit": "$200", "status": "Shipped"},
   // {"order_id": "#6802", "created": "2 min ago", "customers": "Chris Lee", "total": "$430", "profit": "$190", "status": "Pending"},
   // {"order_id": "#7913", "created": "6 min ago", "customers": "Jane Doe", "total": "$150", "profit": "$70", "status": "Delivered"},
   // {"order_id": "#8024", "created": "8 min ago", "customers": "Emily Davis", "total": "$310", "profit": "$187", "status": "Processing"},
   // {"order_id": "#9135", "created": "4 min ago", "customers": "Alice Johnson", "total": "$225", "profit": "$110", "status": "Confirmed"},
   // {"order_id": "#0246", "created": "5 min ago", "customers": "Jon Smit", "total": "$499", "profit": "$300", "status": "Cancelled"},
   // {"order_id": "#1358", "created": "7 min ago", "customers": "Chris Lee", "total": "$108", "profit": "$60", "status": "Pending"},
   // {"order_id": "#2469", "created": "1 min ago", "customers": "Jane Doe", "total": "$330", "profit": "$125", "status": "Shipped"},
   // {"order_id": "#3570", "created": "3 min ago", "customers": "Emily Davis", "total": "$287", "profit": "$150", "status": "Delivered"},
   // {"order_id": "#4681", "created": "5 min ago", "customers": "Alice Johnson", "total": "$450", "profit": "$220", "status": "Processing"},
   // {"order_id": "#5792", "created": "2 min ago", "customers": "Jon Smit", "total": "$175", "profit": "$85", "status": "Confirmed"},
   // {"order_id": "#6803", "created": "6 min ago", "customers": "Chris Lee", "total": "$260", "profit": "$130", "status": "Cancelled"},
   // {"order_id": "#7914", "created": "5 min ago", "customers": "Jane Doe", "total": "$390", "profit": "$200", "status": "Pending"},
   // {"order_id": "#9025", "created": "3 min ago", "customers": "Emily Davis", "total": "$315", "profit": "$178", "status": "Shipped"},
   // {"order_id": "#0136", "created": "8 min ago", "customers": "Alice Johnson", "total": "$420", "profit": "$180", "status": "Delivered"},
   // {"order_id": "#1247", "created": "4 min ago", "customers": "Jon Smit", "total": "$582", "profit": "$302", "status": "Pending"},
   // {"order_id": "#2358", "created": "7 min ago", "customers": "Chris Lee", "total": "$250", "profit": "$135", "status": "Processing"},
   // {"order_id": "#3469", "created": "2 min ago", "customers": "Jane Doe", "total": "$340", "profit": "$180", "status": "Confirmed"},
   // {"order_id": "#4570", "created": "5 min ago", "customers": "Emily Davis", "total": "$455", "profit": "$200", "status": "Cancelled"},
   // {"order_id": "#5681", "created": "1 min ago", "customers": "Alice Johnson", "total": "$190", "profit": "$90", "status": "Pending"},
   // {"order_id": "#6792", "created": "7 min ago", "customers": "Jon Smit", "total": "$350", "profit": "$160", "status": "Shipped"},
   // {"order_id": "#7803", "created": "3 min ago", "customers": "Chris Lee", "total": "$288", "profit": "$102", "status": "Delivered"},
   // {"order_id": "#8914", "created": "6 min ago", "customers": "Jane Doe", "total": "$427", "profit": "$250", "status": "Processing"},
   // {"order_id": "#9025", "created": "5 min ago", "customers": "Emily Davis", "total": "$120", "profit": "$45", "status": "Confirmed"}
];